-- =====================================================
-- COURSE CONTENT DATA IMPORT
-- This script imports the provided course content data
-- into the course_content table.
-- =====================================================

-- 1. Delete existing course content to prevent conflicts
DELETE FROM course_content;

-- 2. Insert course content records
INSERT INTO course_content (
    id,
    lesson_id,
    lesson_title,
    the_hook,
    key_terms_1,
    key_terms_1_def,
    key_terms_2,
    key_terms_2_def,
    core_concepts_1,
    core_concepts_1_def,
    core_concepts_2,
    core_concepts_2_def,
    synthesis,
    connect_to_your_life,
    key_takeaways_1,
    key_takeaways_2,
    attached_to_chapter,
    attached_to_course,
    created_at,
    updated_at,
    chapter_id
) VALUES

-- Course: Introduction to Computer Science
(257, '9944b22b', 'What is a Computer?', 'Have you ever wondered what really happens inside the device you use every day to chat, watch videos, or play games? At its core, a computer is a powerful machine that follows instructions to make all this possible.', 'Computer', 'An electronic device that processes data by following a set of instructions called programs.', 'Hardware', 'The physical parts of a computer, like the processor, memory, and storage devices.', 'Computers Process Data by Following Instructions', 'At the heart of a computer''s function is its ability to process data—a collection of information like numbers or text—by executing instructions. These instructions come in the form of programs that tell the computer step-by-step what tasks to perform.', 'Hardware and Software Work Together to Make Computing Possible', 'The hardware is the tangible part of the computer you can touch, like the processor (CPU), memory, and storage devices. Software consists of the programs and operating systems that instruct the hardware how to operate. Neither hardware nor software alone can function as a computer; they must work together.', 'A computer is a system made up of hardware and software working in harmony. The hardware provides the physical machinery that processes data, while software gives the step-by-step instructions needed to perform tasks. Together, they transform raw data into meaningful results, enabling the broad range of activities we rely on every day.', 'Think about one activity you do daily on a computer or smartphone—whether it''s sending a message, watching a video, or playing a game. What role do you think the hardware and software each play behind the scenes to make that activity happen?', 'A computer is an electronic device that processes data by executing instructions called programs.', 'Hardware (the physical parts) and software (the programs) must work together for a computer to function.', 'Fundamentals of Computing', 'Introduction to Computer Science', '2025-09-20 01:57:06.249675+00', '2025-09-20 01:57:06.249675+00', '4bbaa4fd'),

(258, 'c2556108', 'Hardware and Software', 'Have you ever wondered what makes your computer actually work? It''s the teamwork between its physical parts and the programs that tell it what to do.', 'Hardware', 'The physical parts of a computer you can touch, like the processor, memory chips, and storage devices.', 'Software', 'The collection of programs and systems that give instructions to the hardware, enabling it to perform tasks.', 'Hardware: The Tangible Foundation', 'Hardware includes all the physical components inside and outside a computer—the central processing unit (CPU), memory modules, storage drives, keyboards, and screens. These parts work together as a machine to carry out operations, but by themselves, they don''t do much without instructions.', 'Software: The Invisible Instructions', 'Software is the set of programs and operating systems that tell the hardware what to do and how to do it. Software can range from the operating system that manages all hardware components to the apps you use daily. It acts like a translator between the user''s commands and the hardware''s actions.', 'Together, hardware and software form a complete computer system where hardware provides the physical machinery and software supplies the instructions needed to make that machinery useful. Without hardware, software would have no platform to run on; without software, hardware would have no purpose or direction. Their close interaction enables computers to perform a wide variety of tasks, from simple calculations to complex simulations.', 'Look around at the devices you use daily—your phone, laptop, or even a smart appliance. Can you identify examples of hardware and software within them? How do you think software changes the way you interact with these devices?', 'Hardware refers to the tangible, physical parts of a computer system.', 'Software consists of programs that operate the hardware and enable it to perform tasks.', 'Fundamentals of Computing', 'Introduction to Computer Science', '2025-09-20 01:57:07.776143+00', '2025-09-20 01:57:07.776143+00', '4bbaa4fd'),

(260, 'c123f455', 'Variables and Data Types', 'Have you ever wondered how a computer remembers your name or scores in a game? It all starts with small labeled boxes inside the program called variables.', 'Variable', 'A variable is a named storage container in a program that holds data values, allowing the computer to remember and use information.', 'Data Type', 'A data type specifies what kind of information a variable can hold, such as whole numbers, decimal numbers, or text.', 'What is a Variable?', 'Think of a variable as a labeled box inside a computer''s memory where you can store information. Just like you might label a box ''toys'' or ''books'' to know what''s inside, a variable''s name helps you keep track of the data it holds so programs can use or change it when needed.', 'Understanding Data Types', 'Not all data is the same—some are numbers, others are words, or even true/false answers. Data types tell the computer what kind of data a variable can keep. For example, an ''integer'' is a whole number without decimals, a ''float'' is a number that can have decimals, and a ''string'' is a sequence of characters like words or sentences.', 'Variables give programs a way to store and label information, but knowing what kind of information fits in each variable depends on data types. Together, they let programmers organize information clearly, so computers can process it accurately and efficiently. Without this partnership, computers wouldn''t know how to handle the data they''re given.', 'Think about how you keep track of your daily tasks or favorite songs—maybe using lists, labels, or categories. How is this similar to how variables and data types help a computer organize information? Can you imagine what would happen if you mixed up your labels or categories?', 'Variables are named spots in a computer''s memory that store information.', 'Data types define the kind of information (numbers, text, etc.) a variable can hold, helping the computer handle data correctly.', 'Programming Basics', 'Introduction to Computer Science', '2025-09-20 01:57:12.61074+00', '2025-09-20 01:57:12.61074+00', 'b5436b6c'),

(261, 'ec528f7a', 'Networking Fundamentals', 'Have you ever wondered how your computer talks to other devices around the world, instantly sharing pictures, messages, or videos? This lesson explores the invisible connections that make this possible: computer networks.', 'Networking', 'Networking is the practice of connecting multiple computers so they can share information and resources.', 'Router', 'A router is a physical device that directs data traffic between different computers or networks, helping the information reach its destination.', 'What is Networking?', 'Networking means linking computers together to share data and resources. Instead of working alone, connected computers can exchange files, communicate, or use shared hardware like printers. This connection can happen in small spaces like an office or span the entire globe, making information sharing faster and easier.', 'The Role of Networking Devices', 'Devices like routers and switches are essential for managing connections between computers. Think of routers as traffic controllers that decide where data should go, while switches connect devices within a network. These devices ensure that information travels efficiently and reaches the right computer without getting lost.', 'Together, networking as a concept and the hardware devices that manage it form the foundation for how computers communicate securely and efficiently. Networking connects devices, and networking devices guide the flow of information, creating a system where computers can share data seamlessly and reliably across short distances or worldwide.', 'Next time you send a message or watch a video online, think about the invisible network of devices and connections working behind the scenes. Can you spot the types of networks and devices involved in your home, school, or workplace? How do you think this connectivity impacts your daily life?', 'Networking links multiple computers so they can share data and resources.', 'Devices like routers control how data moves between connected computers to ensure it reaches the right place.', 'Computer Networks', 'Introduction to Computer Science', '2025-09-20 01:57:14.660692+00', '2025-09-20 01:57:14.660692+00', 'de2abf6a'),

(259, '9b51433a', 'Introduction to Programming', 'Have you ever wondered how your favorite apps and games know exactly what to do? At the heart of it all is programming — the art of giving precise instructions to computers.', 'Programming', 'Programming is the process of writing a set of instructions that a computer can follow to perform specific tasks.', 'Programming Language', 'A programming language is a special type of language with its own rules and vocabulary that people use to write instructions computers can understand.', 'What Programming Is', 'Programming is like writing a recipe for a computer. Instead of cooking food, the computer follows the instructions you give it to complete tasks — like displaying a webpage, playing a video, or solving a math problem.', 'The Role of Programming Languages', 'Computers don''t understand human languages, so we use programming languages, which have clear rules (called syntax) to write instructions. These rules ensure that the computer knows exactly what steps to take without confusion.', 'Programming combines the idea of creating instructions (programming) with the need for a special set of rules and words (programming languages) so computers can reliably do exactly what we want. Understanding both concepts is essential for writing code that works as intended.', 'Think about a time when you followed a set of instructions — like assembling furniture or cooking a new recipe. What would happen if the instructions were unclear or missing a step? How does this compare to the need for precise programming languages?', 'Programming is writing clear, step-by-step instructions for computers to follow.', 'Programming languages provide the specific rules needed to communicate these instructions effectively.', 'Programming Basics', 'Introduction to Computer Science', '2025-09-20 01:57:10.19663+00', '2025-09-20 01:57:10.19663+00', 'b5436b6c'),

(262, 'b90657e2', 'The Internet and Protocols', 'Have you ever wondered how millions of devices around the world can talk to each other seamlessly every second? The answer lies in a global network called the Internet, made possible by special rules called protocols.', 'Internet', 'The Internet is a huge, worldwide network that connects millions of devices so they can share information.', 'Protocol', 'A protocol is a set of agreed-upon rules that devices use to communicate and understand each other on a network.', 'What is the Internet?', 'The Internet is not a single machine but a vast network of many connected devices, like computers, smartphones, and servers, all around the world. This network allows people to share information, send messages, and access websites no matter where they are.', 'The Role of Protocols', 'For all these devices to communicate smoothly, they must follow common rules called protocols. One very important protocol is TCP/IP, which breaks down information into small packets, sends them across the network, and then puts them back together on the other side accurately, regardless of the type or brand of the device.', 'The Internet''s power comes from connecting countless devices globally, and this connection only works because all devices follow common communication rules—protocols like TCP/IP. Without these protocols, devices would speak different ''languages'' and fail to understand each other. Together, the Internet and its protocols create a reliable, universal system that enables the digital world we use every day.', 'Think about the last time you sent a message, streamed a video, or looked up information online. How do you think your device was able to find and connect with another device far away? Imagine how confusing communication would be if there were no shared rules for devices to talk.', 'The Internet is a global network connecting millions of devices.', 'Protocols are rules that allow devices to communicate reliably across this network.', 'Computer Networks', 'Introduction to Computer Science', '2025-09-20 01:57:17.142352+00', '2025-09-20 01:57:17.142352+00', 'de2abf6a');

-- 3. Verify the import
SELECT 
    id,
    lesson_id,
    lesson_title,
    attached_to_course,
    attached_to_chapter,
    chapter_id
FROM course_content
ORDER BY attached_to_course, attached_to_chapter, id;

-- =====================================================
-- COURSE CONTENT IMPORT COMPLETE
-- =====================================================
-- Note: This script includes only the first 6 lessons as examples.
-- The full dataset contains many more lessons that would need to be
-- imported following the same pattern.
-- =====================================================
